version: '3.7'

services:

  server:
    container_name: st-server
    image: significant-trades-server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKDIR=${WORKDIR}
        - FILES_LOCATION=${FILES_LOCATION}
        - PORT=${SERVER_PORT}
        - INFLUX_URL=influxdb:${INFLUX_PORT}
        - STORAGE=${STORAGE}
    volumes:
      - ./${FILES_LOCATION}:${WORKDIR}/${FILES_LOCATION}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - influxdb

  influxdb:
    container_name: st-influxdb
    image: influxdb
    ports:
      - ${INFLUX_PORT}:${INFLUX_PORT}
    volumes:
      - ./${FILES_LOCATION}/influxdb:/var/lib/influxdb
    restart: always

  chronograf:
    container_name: st-chronograf
    image: chronograf
    ports:
      - ${CHRONOGRAF_PORT}:${CHRONOGRAF_PORT}
    environment:
      INFLUXDB_URL: http://influxdb:${INFLUX_PORT}
      KAPACITOR_URL: http://kapacitor:${KAPACITOR_PORT}
    volumes:
      - ./${FILES_LOCATION}/chronograf:/var/lib/chronograf
    links:
      - influxdb
      - kapacitor
    depends_on:
      - influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf
    container_name: st-telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    depends_on:
      - influxdb
    restart: unless-stopped

  kapacitor:
    image: kapacitor
    container_name: st-kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:${INFLUX_PORT}
    links:
      - influxdb
    ports:
      - ${KAPACITOR_PORT}:${KAPACITOR_PORT}
    depends_on:
      - influxdb
    restart: unless-stopped
